### ISSUE TITLE
[Feature request] Улучшение для кнопок по умолчанию + Middleware при отсутствии сборщика

### ISSUE THREAD

**Issue by RusAnonym** [MrZillaGold/vk-io-pages#4]
1. Подсветку для клавиатуры, например если следующей страницы не существуют то кнопка для перехода становится красной.

2. Функция обрабатывающая сообщение если таймер прослушивания уже истек, а сообщение относится к нему.

**Comment by MrZillaGold** [comment]
1. Думаю можно будет реализовать полное удаление кнопок если страниц дальше/в начале нет и infinityLoop выключен.

2. Добавлю middleware.

**Comment by MrZillaGold** [comment]
Доступно в [последнем релизе](https://github.com/MrZillaGold/vk-io-pages/releases/tag/1.3.0)
